### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by arihantparsoya** [parsoyaarihant/vision#7]
I ran the test file and here is the output

```
OpenCV Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /tmp/opencv20160107-29960-t5glvv/opencv-2.4.12/modules/imgproc/src/color.cpp, line 3739
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    print resize_model('image/man_frontf.png','image/man_side.jpg','image/man.jpg')
  File "/Users/parsoyaarihant/vision/resize_model.py", line 7, in resize_model
    mf=encContour(mfront)
  File "/Users/parsoyaarihant/vision/outer.py", line 6, in encContour
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
cv2.error: /tmp/opencv20160107-29960-t5glvv/opencv-2.4.12/modules/imgproc/src/color.cpp:3739: error: (-215) scn == 3 || scn == 4 in function cvtColor
```

@rahulraj1255 @Pritamkn

**Comment by rahulraj1255** [comment]
resize_model takes image name only in current directory not in a folder.

**Comment by rahulraj1255** [comment]
image read hi nahi ho rha hai

**Comment by arihantparsoya** [comment]
haan i got it but we have to do something for this. we cant keep so many images in the same directory
